params:
  seed: 42
  
  # environment wrapper clipping
  env:
    # added to the wrapper
    clip_observations: 1000.0
    # can make custom wrapper?
    clip_actions: 1.0

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    ### MLP ###
    name: mlp_net
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      # units: [4096, 2048, 1024]
      # units: [2048, 1024, 512]
      units: [512, 256, 128]  
      # units: [256, 128, 64]     
      activation: elu
      d2rl: False
      initializer:
        name: default
      regularizer:
        name: None

    ### RMA ###
    # name: rma
    # separate: False
    # space:
    #   continuous:
    #     mu_activation: None
    #     sigma_activation: None
    #     mu_init:
    #       name: default
    #     sigma_init:
    #       name: const_initializer
    #       val: 0
    #     fixed_sigma: True
    # mlp:
    #   units: [ 256, 128, 64 ]
    #   dense_func: Linear
    #   activation: elu
    # cnn:
    #   ctype: conv1d
    #   activation: relu
    #   convs:
    #     - filters: 128
    #       kernel_size: 3
    #       strides: 1
    #       padding: 0
    #     - filters: 128
    #       kernel_size: 3
    #       strides: 1
    #       padding: 0
    #     - filters: 128
    #       kernel_size: 3
    #       strides: 1
    #       padding: 0

    ### MLP + RNN ###
    # name: mlp_rnn
    # separate: False
    # space:
    #   continuous:
    #     mu_activation: None
    #     sigma_activation: None
    #     mu_init:
    #       name: default
    #     sigma_init:
    #       name: const_initializer
    #       val: 0
    #     fixed_sigma: True
    # mlp:
    #   units: [8192, 4096, 2048]
    #   activation: elu
    #   d2rl: False
    #   initializer:
    #     name: default
    #   regularizer:
    #     name: None
  
    # rnn:
    #   name: lstm
    #   units: 1024
    #   layers: 1
    #   before: True
    #   after: False
    
    ### RMA mit TCN ###
    # name: rma_tcn
    # separate: False
    # space:
    #   continuous:
    #     mu_activation: None
    #     sigma_activation: None
    #     mu_init:
    #       name: default
    #     sigma_init:
    #       name: const_initializer
    #       val: 0
    #     fixed_sigma: True
    # mlp:
    #   units: [ 256, 128, 64 ]
    #   dense_func: Linear
    #   activation: elu
    # tcn:
    #   num_channels: [32, 32, 32]   
    #   kernel_size: 3                  
    #   dilations: [1, 2, 4]            
    #   dropout: 0.0                   
    #   causal: True                    
    #   use_norm: weight_norm        
    #   activation: relu
    #   use_skip_connections: False
    #   input_shape: NCL

    ### ACTOR-CRITIC
    # name: actor_critic
    # separate: False

    # space:
    #   continuous:
    #     mu_activation: None
    #     sigma_activation: None
    #     mu_init:
    #       name: default
    #     sigma_init:
    #       name: const_initializer
    #       val: 0
    #     fixed_sigma: True
    # mlp:
    #   units: [2048, 1024, 512]
    #   # units: [1024, 512, 256]
    #   # units: [512, 256, 128]
    #   # units: [256, 128, 64]
    #   activation: relu
    #   d2rl: False

    #   initializer:
    #     name: default
    #   regularizer:
    #     name: None
    # rnn:
    #   name: lstm
    #   units: 1024
    #   layers: 1
    #   before_mlp: True
    #   layer_norm: True




  load_checkpoint: False
  load_path: nn/Robomaster.pth

  config:
    name: 'Robomaster'
    env_name : rlgpu
    device: cuda
    device_id: 0
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    reward_shaper:
      scale_value: 0.1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 100000
    max_epochs: 50000
    save_best_after: 25
    save_frequency: 500
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 32
    minibatch_size: 32768  
    # minibatch_size: 16384
    # minibatch_size: 32
    mini_epochs: 4
    critic_coef: 4
    clip_value: True
    seq_length: 8
    bounds_loss_coef: 0.0001

